server:
  port: 8002

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.joyin.entities

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    #采样率值介于 0 到 1 之间，1 则表示全部采集
    probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.100.76.110:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234Abcd!
  thymeleaf:
    cache: false
    prefix: classpath:/pages/



eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://192.168.101.72:7001/eureka/



